In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

# Initial Webscraping for 1 year/Table

In [2]:
#page = requests.get('https://www.basketball-reference.com/leagues/NBA_2018_standings.html')

In [3]:
#content = page.content

In [12]:
#soup = BeautifulSoup(content, 'html.parser')
#table = soup.find(name='table', attrs={'id':'confs_standings_E'})

In [13]:
#table

<table class="suppress_all sortable stats_table" data-cols-to-freeze="1" id="confs_standings_E"><caption>Conference Standings Table</caption>
<colgroup><col/><col/><col/><col/><col/><col/><col/><col/></colgroup>
<thead>
<tr>
<th aria-label="Eastern Conference" class="poptip sort_default_asc left" data-stat="team_name" scope="col">Eastern Conference</th>
<th aria-label="Wins" class="poptip center" data-stat="wins" data-tip="Wins" scope="col">W</th>
<th aria-label="Losses" class="poptip center" data-stat="losses" data-tip="Losses" scope="col">L</th>
<th aria-label="Win-Loss Percentage" class="poptip right" data-stat="win_loss_pct" data-tip="Win-Loss Percentage" scope="col">W/L%</th>
<th aria-label="Games Behind" class="poptip sort_default_asc right" data-stat="gb" data-tip="Games Behind" scope="col">GB</th>
<th aria-label="Points Per Game" class="poptip right" data-stat="pts_per_g" data-tip="Points Per Game" scope="col">PS/G</th>
<th aria-label="Opponent Points Per Game" class="poptip right" data-stat="opp_pts_per_g" data-tip="Opponent Points Per Game" scope="col">PA/G</th>
<th aria-label="Simple Rating System" class="poptip center" data-stat="srs" data-tip="Simple Rating System; a team rating that takes into account average point differential and strength of schedule. The rating is denominated in points above/below average, where zero is average." scope="col">SRS</th>
</tr>
</thead>
<tbody>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/TOR/2018.html">Toronto Raptors</a>* <span class="seed">(1) </span></th><td class="right" data-stat="wins">59</td><td class="right" data-stat="losses">23</td><td class="right" data-stat="win_loss_pct">.720</td><td class="right" data-stat="gb">—</td><td class="right" data-stat="pts_per_g">111.7</td><td class="right" data-stat="opp_pts_per_g">103.9</td><td class="right" data-stat="srs">7.29</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/BOS/2018.html">Boston Celtics</a>* <span class="seed">(2) </span></th><td class="right" data-stat="wins">55</td><td class="right" data-stat="losses">27</td><td class="right" data-stat="win_loss_pct">.671</td><td class="right" data-stat="gb">4.0</td><td class="right" data-stat="pts_per_g">104.0</td><td class="right" data-stat="opp_pts_per_g">100.4</td><td class="right" data-stat="srs">3.23</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/PHI/2018.html">Philadelphia 76ers</a>* <span class="seed">(3) </span></th><td class="right" data-stat="wins">52</td><td class="right" data-stat="losses">30</td><td class="right" data-stat="win_loss_pct">.634</td><td class="right" data-stat="gb">7.0</td><td class="right" data-stat="pts_per_g">109.8</td><td class="right" data-stat="opp_pts_per_g">105.3</td><td class="right" data-stat="srs">4.30</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CLE/2018.html">Cleveland Cavaliers</a>* <span class="seed">(4) </span></th><td class="right" data-stat="wins">50</td><td class="right" data-stat="losses">32</td><td class="right" data-stat="win_loss_pct">.610</td><td class="right" data-stat="gb">9.0</td><td class="right" data-stat="pts_per_g">110.9</td><td class="right" data-stat="opp_pts_per_g">109.9</td><td class="right" data-stat="srs">0.59</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/IND/2018.html">Indiana Pacers</a>* <span class="seed">(5) </span></th><td class="right" data-stat="wins">48</td><td class="right" data-stat="losses">34</td><td class="right" data-stat="win_loss_pct">.585</td><td class="right" data-stat="gb">11.0</td><td class="right" data-stat="pts_per_g">105.6</td><td class="right" data-stat="opp_pts_per_g">104.2</td><td class="right" data-stat="srs">1.18</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/MIA/2018.html">Miami Heat</a>* <span class="seed">(6) </span></th><td class="right" data-stat="wins">44</td><td class="right" data-stat="losses">38</td><td class="right" data-stat="win_loss_pct">.537</td><td class="right" data-stat="gb">15.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">102.9</td><td class="right" data-stat="srs">0.15</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/MIL/2018.html">Milwaukee Bucks</a>* <span class="seed">(7) </span></th><td class="right" data-stat="wins">44</td><td class="right" data-stat="losses">38</td><td class="right" data-stat="win_loss_pct">.537</td><td class="right" data-stat="gb">15.0</td><td class="right" data-stat="pts_per_g">106.5</td><td class="right" data-stat="opp_pts_per_g">106.8</td><td class="right" data-stat="srs">-0.45</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/WAS/2018.html">Washington Wizards</a>* <span class="seed">(8) </span></th><td class="right" data-stat="wins">43</td><td class="right" data-stat="losses">39</td><td class="right" data-stat="win_loss_pct">.524</td><td class="right" data-stat="gb">16.0</td><td class="right" data-stat="pts_per_g">106.6</td><td class="right" data-stat="opp_pts_per_g">106.0</td><td class="right" data-stat="srs">0.53</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/DET/2018.html">Detroit Pistons</a> <span class="seed">(9) </span></th><td class="right" data-stat="wins">39</td><td class="right" data-stat="losses">43</td><td class="right" data-stat="win_loss_pct">.476</td><td class="right" data-stat="gb">20.0</td><td class="right" data-stat="pts_per_g">103.8</td><td class="right" data-stat="opp_pts_per_g">103.9</td><td class="right" data-stat="srs">-0.26</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CHO/2018.html">Charlotte Hornets</a> <span class="seed">(10) </span></th><td class="right" data-stat="wins">36</td><td class="right" data-stat="losses">46</td><td class="right" data-stat="win_loss_pct">.439</td><td class="right" data-stat="gb">23.0</td><td class="right" data-stat="pts_per_g">108.2</td><td class="right" data-stat="opp_pts_per_g">108.0</td><td class="right" data-stat="srs">0.07</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/NYK/2018.html">New York Knicks</a> <span class="seed">(11) </span></th><td class="right" data-stat="wins">29</td><td class="right" data-stat="losses">53</td><td class="right" data-stat="win_loss_pct">.354</td><td class="right" data-stat="gb">30.0</td><td class="right" data-stat="pts_per_g">104.5</td><td class="right" data-stat="opp_pts_per_g">108.0</td><td class="right" data-stat="srs">-3.53</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/BRK/2018.html">Brooklyn Nets</a> <span class="seed">(12) </span></th><td class="right" data-stat="wins">28</td><td class="right" data-stat="losses">54</td><td class="right" data-stat="win_loss_pct">.341</td><td class="right" data-stat="gb">31.0</td><td class="right" data-stat="pts_per_g">106.6</td><td class="right" data-stat="opp_pts_per_g">110.3</td><td class="right" data-stat="srs">-3.67</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/CHI/2018.html">Chicago Bulls</a> <span class="seed">(13) </span></th><td class="right" data-stat="wins">27</td><td class="right" data-stat="losses">55</td><td class="right" data-stat="win_loss_pct">.329</td><td class="right" data-stat="gb">32.0</td><td class="right" data-stat="pts_per_g">102.9</td><td class="right" data-stat="opp_pts_per_g">110.0</td><td class="right" data-stat="srs">-6.84</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/ORL/2018.html">Orlando Magic</a> <span class="seed">(14) </span></th><td class="right" data-stat="wins">25</td><td class="right" data-stat="losses">57</td><td class="right" data-stat="win_loss_pct">.305</td><td class="right" data-stat="gb">34.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">108.2</td><td class="right" data-stat="srs">-4.92</td></tr>
<tr class="full_table"><th class="left" data-stat="team_name" scope="row"><a href="/teams/ATL/2018.html">Atlanta Hawks</a> <span class="seed">(15) </span></th><td class="right" data-stat="wins">24</td><td class="right" data-stat="losses">58</td><td class="right" data-stat="win_loss_pct">.293</td><td class="right" data-stat="gb">35.0</td><td class="right" data-stat="pts_per_g">103.4</td><td class="right" data-stat="opp_pts_per_g">108.8</td><td class="right" data-stat="srs">-5.30</td></tr>
</tbody></table>

In [15]:
#html_str = str(table)
#df = pd.read_html(html_str)[0]

In [17]:
#df

          Eastern Conference   W   L   W/L%    GB   PS/G   PA/G   SRS
0       Toronto Raptors* (1)  59  23  0.720     —  111.7  103.9  7.29
1        Boston Celtics* (2)  55  27  0.671   4.0  104.0  100.4  3.23
2    Philadelphia 76ers* (3)  52  30  0.634   7.0  109.8  105.3  4.30
3   Cleveland Cavaliers* (4)  50  32  0.610   9.0  110.9  109.9  0.59
4        Indiana Pacers* (5)  48  34  0.585  11.0  105.6  104.2  1.18
5            Miami Heat* (6)  44  38  0.537  15.0  103.4  102.9  0.15
6       Milwaukee Bucks* (7)  44  38  0.537  15.0  106.5  106.8 -0.45
7    Washington Wizards* (8)  43  39  0.524  16.0  106.6  106.0  0.53
8        Detroit Pistons (9)  39  43  0.476  20.0  103.8  103.9 -0.26
9     Charlotte Hornets (10)  36  46  0.439  23.0  108.2  108.0  0.07
10      New York Knicks (11)  29  53  0.354  30.0  104.5  108.0 -3.53
11        Brooklyn Nets (12)  28  54  0.341  31.0  106.6  110.3 -3.67
12        Chicago Bulls (13)  27  55  0.329  32.0  102.9  110.0 -6.84
13        Orlando Magic (14)  25  57  0.305  34.0  103.4  108.2 -4.92
14        Atlanta Hawks (15)  24  58  0.293  35.0  103.4  108.8 -5.30

In [22]:
years = np.arange(2015, 2019, 1)

In [23]:
years

array([2015, 2016, 2017, 2018])

In [49]:
#writing loop to scrape 4 years of eastern conference team info into 1 dataframe

years = np.arange(2015, 2019, 1)

base = 'https://www.basketball-reference.com/leagues/NBA_{}_standings.html'

team_wl = pd.DataFrame()

for year in years:
    url = base.format(year)
    req = requests.get(url)
    soup = BeautifulSoup(req.content, 'html.parser')
    table1 = soup.find(name='table', attrs={'id':'divs_standings_E'})
    html_str1 = str(table1)
    df = pd.read_html(html_str1)[0]
    df['Year'] = year
    
    team_wl = team_wl.append(df)

In [43]:
page1 = requests.get('https://www.basketball-reference.com/leagues/NBA_2018_standings.html')

In [44]:
content1 = page1.content

In [46]:
soup = BeautifulSoup(content, 'html.parser')
table1 = soup.find(name='table', attrs={'id':'divs_standings_E'})

In [47]:
html_str1 = str(table1)
df1 = pd.read_html(html_str1)[0]

In [48]:
df1

,Eastern Conference,W,L,W/L%,GB,PS/G,PA/G,SRS
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division
1,Toronto Raptors* (1),59,23,.720,—,111.7,103.9,7.29
2,Boston Celtics* (2),55,27,.671,4.0,104.0,100.4,3.23
3,Philadelphia 76ers* (3),52,30,.634,7.0,109.8,105.3,4.30
4,New York Knicks (11),29,53,.354,30.0,104.5,108.0,-3.53
5,Brooklyn Nets (12),28,54,.341,31.0,106.6,110.3,-3.67
6,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division
7,Cleveland Cavaliers* (4),50,32,.610,—,110.9,109.9,0.59
8,Indiana Pacers* (5),48,34,.585,2.0,105.6,104.2,1.18
9,Milwaukee Bucks* (7),44,38,.537,6.0,106.5,106.8,-0.45
10,Detroit Pistons (9),39,43,.476,11.0,103.8,103.9,-0.26
11,Chicago Bulls (13),27,55,.329,23.0,102.9,110.0,-6.84
12,Southeast Division,Southeast Division,Southeast Division,Southeast Division,Southeast Division,Southeast Division,Southeast Division,Southeast Division
13,Miami Heat* (6),44,38,.537,—,103.4,102.9,0.15
14,Washington Wizards* (8),43,39,.524,1.0,106.6,106.0,0.53
15,Charlotte Hornets (10),36,46,.439,8.0,108.2,108.0,0.07
16,Orlando Magic (14),25,57,.305,19.0,103.4,108.2,-4.92
17,Atlanta Hawks (15),24,58,.293,20.0,103.4,108.8,-5.30

In [51]:
team_wl

,Eastern Conference,W,L,W/L%,GB,PS/G,PA/G,SRS,Year
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,2015
1,Toronto Raptors* (4),49,33,.598,—,104.0,100.9,2.45,2015
2,Boston Celtics* (7),40,42,.488,9.0,101.4,101.2,-0.40,2015
3,Brooklyn Nets* (8),38,44,.463,11.0,98.0,100.9,-3.13,2015
4,Philadelphia 76ers (14),18,64,.220,31.0,92.0,101.0,-9.04,2015
...,...,...,...,...,...,...,...,...,...
13,Miami Heat* (6),44,38,.537,—,103.4,102.9,0.15,2018
14,Washington Wizards* (8),43,39,.524,1.0,106.6,106.0,0.53,2018
15,Charlotte Hornets (10),36,46,.439,8.0,108.2,108.0,0.07,2018
16,Orlando Magic (14),25,57,.305,19.0,103.4,108.2,-4.92,2018
17,Atlanta Hawks (15),24,58,.293,20.0,103.4,108.8,-5.30,2018

In [53]:
#writing loop to scrape 4 years of western conference division info into 1 dataframe

years = np.arange(2015, 2019, 1)

base = 'https://www.basketball-reference.com/leagues/NBA_{}_standings.html'

team_wl1 = pd.DataFrame()

for year in years:
    url = base.format(year)
    req = requests.get(url)
    soup = BeautifulSoup(req.content, 'html.parser')
    table1 = soup.find(name='table', attrs={'id':'divs_standings_W'})
    html_str1 = str(table1)
    df = pd.read_html(html_str1)[0]
    df['Year'] = year
    
    team_wl1 = team_wl1.append(df)

In [54]:
team_wl1

,Western Conference,W,L,W/L%,GB,PS/G,PA/G,SRS,Year
0,Northwest Division,Northwest Division,Northwest Division,Northwest Division,Northwest Division,Northwest Division,Northwest Division,Northwest Division,2015
1,Portland Trail Blazers* (4),51,31,.622,—,102.8,98.6,4.41,2015
2,Oklahoma City Thunder (9),45,37,.549,6.0,104.0,101.8,2.47,2015
3,Utah Jazz (11),38,44,.463,13.0,95.1,94.9,0.71,2015
4,Denver Nuggets (12),30,52,.366,21.0,101.5,105.0,-3.07,2015
...,...,...,...,...,...,...,...,...,...
13,Houston Rockets* (1),65,17,.793,—,112.4,103.9,8.21,2018
14,New Orleans Pelicans* (6),48,34,.585,17.0,111.7,110.4,1.48,2018
15,San Antonio Spurs* (7),47,35,.573,18.0,102.7,99.8,2.89,2018
16,Dallas Mavericks (13),24,58,.293,41.0,102.3,105.4,-2.70,2018
17,Memphis Grizzlies (14),22,60,.268,43.0,99.3,105.5,-5.81,2018

# Cleaning DataFrames

In [59]:
team_wl.columns

Index(['Eastern Conference', 'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G', 'SRS',
       'Year'],
      dtype='object')

In [65]:
#dropping unnecessary columns
team_wl = team_wl.drop(['W/L%', 'GB', 'PS/G', 'PA/G', 'SRS'], axis = 1)

In [66]:
team_wl.head()

        Eastern Conference                  W                  L  Year
0        Atlantic Division  Atlantic Division  Atlantic Division  2015
1     Toronto Raptors* (4)                 49                 33  2015
2      Boston Celtics* (7)                 40                 42  2015
3       Brooklyn Nets* (8)                 38                 44  2015
4  Philadelphia 76ers (14)                 18                 64  2015

In [69]:
#dropping unnecessary rows with division name
team_wl = team_wl[team_wl['Eastern Conference'] != 'Atlantic Division']

In [71]:
team_wl = team_wl[team_wl['Eastern Conference'] != 'Central Division']

In [72]:
team_wl = team_wl[team_wl['Eastern Conference'] != 'Southeast Division']

In [73]:
team_wl.shape

(60, 4)

In [74]:
#dropping columns for WC dataframe
team_wl1 = team_wl1.drop(['W/L%', 'GB', 'PS/G', 'PA/G', 'SRS'], axis = 1)

In [76]:
#dropping unnecessary rows
team_wl1 = team_wl1[team_wl1['Western Conference'] != 'Northwest Division']

In [77]:
team_wl1 = team_wl1[team_wl1['Western Conference'] != 'Pacific Division']

In [78]:
team_wl1 = team_wl1[team_wl1['Western Conference'] != 'Southwest Division']

In [80]:
team_wl1.shape

(60, 4)

## Cleaning Dataframes